version: '3.3'
services:

  # PROXY #####################################################################################
  same-proxy:
    image: traefik:1.7.4-alpine
    labels:
      - "traefik.frontend.rule=Host:monitor.salesmeet.it"
      - "traefik.port=8080"
      - "traefik.docker.network=samenetwork"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/traefik/
    ports:
      - "80:80"
      - "443:443"
      - '8080:8080'
    networks:
      - samenetwork
    command: -c /dev/null --web --docker --logLevel=DEBUG --defaultEntryPoints='https,http' --entryPoints="Name:https Address::443 TLS:/traefik/cert.pem,/traefik/privkey.pem" --entryPoints="Name:http Address::80"

  # plugin #################
  same-plugin:
    build: ./sameplugin
    labels:
      - "traefik.backend=same-plugin"
      - "traefik.frontend.rule=Host:plugin.salesmeet.it"
      - "traefik.docker.network=samenetwork"
    volumes:
      - ./sameplugin/src:/var/www/html
    networks:
      - samenetwork

  # plugin #################
  same-api:
    build: ./sameapi
    labels:
      - "traefik.backend=same-api"
      - "traefik.frontend.rule=Host:api.salesmeet.it"
      - "traefik.docker.network=samenetwork"
    volumes:
      - ./sameapi/src:/var/www/html
    networks:
      - samenetwork

networks:
  samenetwork:
    external: true
